source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'GoogleDirectionKit_Example' do
  pod 'GoogleDirectionKit', :path => '../'
  
  target 'GoogleDirectionKit_Tests' do
    inherit! :search_paths

    
  end
end
