source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'GoogleDirectionKit_Example' do
  pod 'GoogleDirectionKit', :path => '../'
#  pod 'YYModel', '~> 1.0.4'
  
  target 'GoogleDirectionKit_Tests' do
    inherit! :search_paths

    
  end
end
